name: C++ Build with Static Linking


on:
  workflow_dispatch:

jobs:
  build:
    name: Build C++ Application
    runs-on: ubuntu-latest  # You can also use windows-latest if you need a Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCC
        run: |
          sudo apt update
          sudo apt install -y g++  # For Ubuntu; for Windows, you would configure MSVC or MinGW

      - name: Build C++ application with static linking
        run: |
          g++ -static main.cpp allclasses.cpp -o app.exe

      - name: List files
        run: ls -l  # Optional: to verify the generated app.exe file

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: app-executable
          path: app.exe
